---
# use this playbook to config a server, and tack any role you need to this
- name: Preparing home server! 
  gather_facts: false
  hosts: all
  remote_user: zappy
  vars_files:
    - variables.yml
  roles:
    - common
    - fileserver
    - deluge
    - expressvpn
    - plex
    - nessus