---
# Run common tasks on this server 

- name: Enabling user as sudoer without requiring a password
  command: echo "zappy ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/zappy ; chmod 0440 /etc/sudoers.d/zappy ;
  become: yes

- name: Uninstalling python 3 =( (Ansible Docker Modules require Python2)
  apt:
    name: [python3, python3-pip]
    state: absent

- name: Installing Python2, pip2
  apt:
    name: [python, python-pip]

- name: Install requests module
  pip:
    name: requests