---
# Run common tasks on this server 

- name: "Changing hostname to {{ hostname }}"
  hostname:
    name: "{{ hostname }}"

- name: Enabling user as sudoer without requiring a password
  replace:
    path: /etc/sudoers.d/zappy
    regexp: 'dummy'
    replace: 'zappy'

#   command: chmod 0740 /etc/sudoers.d/zappy; echo "zappy ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/zappy ; chmod 0440 /etc/sudoers.d/zappy ;
#   become: yes

- name: Install requests module
  pip:
    name: requests

- name: Install Pexpect module
  apt:
    name: python-pexpect

# if this is vmware box (for me it usually is)
# installing the open vm tools is easier and more straightforward
# then doing VMWare's
- name: Install vmware tools
  apt:
    name: open-vm-tools

- name: Install VIM
  apt:
    name: vim

- name: Install net-tools
  apt:
    name: net-tools