---
# Run common tasks on this server 

- name: "Changing hostname to {{ hostname }}"
  hostname:
    name: "{{ hostname }}"

- name: Enabling user as sudoer without requiring a password
  replace:
    path: /etc/sudoers.d/zappy
    regexp: 'dummy'
    replace: 'zappy'

#   command: chmod 0740 /etc/sudoers.d/zappy; echo "zappy ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/zappy ; chmod 0440 /etc/sudoers.d/zappy ;
#   become: yes

- name: Install requests module
  pip:
    name: requests

- name: Install Pexpect module
  apt:
    name: python-pexpect

# if this is vmware box (for me it usually is)
# installing the open vm tools is easier and more straightforward
# then doing VMWare's
- name: Install vmware tools
  apt:
    name: open-vm-tools

- name: Install VIM
  apt:
    name: vim

- name: Install net-tools
  apt:
    name: net-tools

- name: Install unrar
  apt:
    name: unrar

- name: Install iperf
  apt:
    name: iperf

- name: Install curl
  apt:
    name: curl

# update thoe /etc/hosts file to have the hostname
- name: Update the hosts file with the server name
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 {{ hostname }}'
    owner: root
    group: root
    mode: 0644